server.port=8082
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
spring.datasource.url=jdbc:postgresql://localhost:5432/educloud
spring.datasource.username=user
spring.datasource.password=password
