server.port=8080
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/

# Ruta 1: Inscripciones
spring.cloud.gateway.server.webmvc.routes[0].id=servicio-inscripciones
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://EDUCLOUD-INSCRIPCIONES
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api/inscripcion/**